### ISSUE TITLE
Proposal: `fud install`

### ISSUE THREAD

**Issue by rachitnigam** [sampsyo/fake#2]
For some tools that `fud` uses, installing it is straightforward. For example, installing `vcdump` is as straightforward as `cargo install vcdump`. Should we provide some declarative way to specify how to install tools on a particular platform:
```toml
name = "vcdump"

[install.x86]
cmd = "cargo install vcdump"

[install.arm64]
cmd = "curl ... | sh"
```
